[package]
name = "rustdoc-json-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rustdoc-types = "0.46.1"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
